
services:

  endpoint-redis:
    container_name: endpoint-redis
    build:
      context: ./build/libs
      dockerfile: ./Dockerfile
    image: endpoint-redis:latest
    ports:
      - '8080:8080'
    environment:
      ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
      JAR_NAME: endpoint-0.0.1-SNAPSHOT.jar
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_STREAMING_QUEUE: si.test.queue
      REDIS_RULE_QUEUE: si.ceprule.queue
    networks:
      - redis_go_net

networks:
  redis_go_net:
    driver: bridge
    external: true