version: '3.9'
services:
  redis-server:
    container_name: "redis-server"
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - redis_go_net
    volumes:
      - ./redis-volume:/data


  streamingflow4j-redis:
    container_name: streamingflow4j-redis
    build:
      context: ./build/libs
      dockerfile: ./Dockerfile
    image: streamingflow4j-redis:latest
    ports:
      - '8181:8181'
    environment:
      JAR_NAME: streamingflow4j-0.0.1-SNAPSHOT.jar
      REDIS_HOST: 172.19.0.2
      REDIS_PORT: 6379
      REDIS_STREAMING_QUEUE: si.test.queue
      REDIS_RULE_QUEUE: si.ceprule.queue
    links:
      - redis-server
    depends_on:
      - redis-server
    networks:
      - redis_go_net

networks:
  redis_go_net:
    driver: bridge