version: '3.9'
services:

  redis:
    container_name: redis
    hostname: redis
    image: 'redis:latest'
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - redis_go_net
    volumes:
      - ./redis-volume:/data

  streamingflow4j-redis:
    container_name: streamingflow4j-redis
    build:
      context: ./build/libs
      dockerfile: ./Dockerfile
    image: streamingflow4j-redis:latest
    ports:
      - '8181:8181'
    environment:
      JAR_NAME: streamingflow4j-0.0.1-SNAPSHOT.jar
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_STREAMING_QUEUE: si.test.queue
      REDIS_RULE_QUEUE: si.ceprule.queue
    links:
      - redis
    depends_on:
      - redis
    networks:
      - redis_go_net

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    networks:
      - redis_go_net


networks:
  redis_go_net:
    driver: bridge
    external: true